---
runtime: shiny
title: "Monte carlo simulation"
output: flexdashboard::flex_dashboard
---


```{r}
knitr::opts_chunk$set(echo=F, message=TRUE, warning=TRUE)
library(ggplot2)
library(DT)
```

```{r}
per_step = 100

rad=1
min=-1
max=min+2*rad

angle = seq(-pi, pi, length = 50)
circle = data.frame(x = sin(angle), y = cos(angle))
```

Sidebar {.sidebar}
=====================================

The aim of this exercise is to simulate the value of $\pi$.

```{r}
actionButton("add", "Add")
```

```{r}
renderText({ 
    paste("Counter: ", values$counter*per_step)
})
```

```{r}
renderText({ 
    if(dim(values$data)[1] >= 1) {
        pi_sim = 4*sum(values$data$inside==1)/length(values$data$inside)
        paste("Simulated pi: ", round(pi_sim, 7))
    }
})
```

Real $\pi$ = `r pi`<br>

First, we draw a circle and a square.

1. Randomly draw x,y coordinates in square. 
2. Check if coordinates falls within the circle using formula
$x^2 + y^2 < R^2$, where $R$ is the radius of the circle. 
3. Tally number of points in circle/ number of points in square. 


$A_s = 2R * 2R = 4R^2$ <br>
$A_c = \pi * R^2$ <br>
$\frac{A_c}{A_s} = \frac{\pi * R^2}{4R^2} = \frac{\pi}{4}$ <br>

The simulated value of pi should be $\pi = 4 * \frac{number of points in circle}{number of points in square}$


```{r}
values = reactiveValues()
values$counter = 0
values$data = data.frame(x=numeric(), y=numeric(), inside=integer())
observeEvent(input$add, { 
    values$counter = values$counter + 1
    x = runif(per_step, min=min, max=max)
    y = runif(per_step, min=min, max=max)
    inside = ifelse(x^2 + y^2 < max^2, 1, 0) 
    values$data = rbind(values$data, data.frame(x=x, y=y, inside=inside))
})

output$data = renderDataTable({values$data})
```

Page 1
=====================================  

```{r}
renderPlot({
    ggplot(values$data, aes(x=x, y=y, color=factor(inside))) + 
        geom_polygon(aes(x, y), data = circle, inherit.aes = F) + 
        geom_point() +
        theme_minimal() +
        scale_x_continuous(limits=c(min,max)) +
        scale_y_continuous(limits=c(min,max)) +
        guides(color=FALSE)
        
    
}, width = 500, height = 500)
```

Page 2
=====================================  
```{r}
dataTableOutput("data")
```